// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('🔍 SUPABASE CLIENT: Initializing with enhanced timeout settings:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_ANON_KEY,
  keyPreview: SUPABASE_ANON_KEY?.substring(0, 20) + '...'
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    // Enhanced auth configuration for better timeout handling
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Increase timeout for auth operations
    flowType: 'pkce'
  },
  global: {
    // Enhanced fetch configuration for better network resilience
    fetch: (url, options = {}) => {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => {
        console.error('🚨 SUPABASE CLIENT: Network request timeout after 15000ms for:', url);
        controller.abort();
      }, 15000); // 15s timeout - more reasonable for user-facing operations
      
      const requestOptions = options as RequestInit;
      
      return fetch(url, {
        ...requestOptions,
        signal: controller.signal,
        // Add retry headers for better network handling
        headers: {
          ...(requestOptions.headers || {}),
          'Cache-Control': 'no-cache',
          'Connection': 'keep-alive'
        }
      }).catch(error => {
        if (error.name === 'AbortError') {
          console.error('🚨 SUPABASE CLIENT: Request aborted due to timeout for:', url);
          throw new Error('Network request timeout - Supabase Client');
        }
        throw error;
      }).finally(() => {
        clearTimeout(timeoutId);
      });
    }
  },
  db: {
    // Database connection settings
    schema: 'public'
  },
  realtime: {
    // Realtime connection settings for better stability
    params: {
      eventsPerSecond: 10
    }
  }
});