// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bzzstdpfmyqttnzhgaoa.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6enN0ZHBmbXlxdHRuemhnYW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzI5NzMsImV4cCI6MjA2NDA0ODk3M30.NXT4XRuPilV2AV6KYY56-vk3AqZ8I2DQKkVjfbMcWoI";

console.log('🔍 SUPABASE CLIENT: Initializing with enhanced timeout settings:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_ANON_KEY,
  keyPreview: SUPABASE_ANON_KEY?.substring(0, 20) + '...',
  envVars: {
    VITE_SUPABASE_URL: !!import.meta.env.VITE_SUPABASE_URL,
    VITE_SUPABASE_ANON_KEY: !!import.meta.env.VITE_SUPABASE_ANON_KEY,
    VITE_SUPABASE_PUBLISHABLE_KEY: !!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  }
});

// Validate that we have the required configuration
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('🚨 SUPABASE CLIENT: Missing required configuration!', {
    url: SUPABASE_URL,
    hasKey: !!SUPABASE_ANON_KEY
  });
  throw new Error('Supabase configuration is incomplete');
}

// Custom fetch with timeout to prevent indefinite hangs
const fetchWithTimeout = (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const timeout = 30000; // 30 second timeout for all requests
  const controller = new AbortController();
  const timeoutId = setTimeout(() => {
    console.warn('🚨 SUPABASE CLIENT: Request timeout, aborting:', url);
    controller.abort();
  }, timeout);

  return fetch(url, {
    ...options,
    signal: controller.signal
  }).finally(() => clearTimeout(timeoutId));
};

// No-op lock function to prevent deadlocks caused by Web Locks API issues
// See: https://github.com/supabase/supabase-js/issues/1594
const noOpLock = async <T>(
  _name: string,
  _acquireTimeout: number,
  fn: () => Promise<T>
): Promise<T> => {
  return await fn();
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    // Enhanced auth configuration for better timeout handling
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // CRITICAL: Use no-op lock to prevent deadlocks
    // This fixes the issue where GoTrueClient hangs on lock acquisition
    lock: noOpLock
  },
  db: {
    // Database connection settings
    schema: 'public'
  },
  global: {
    // Use custom fetch with timeout
    fetch: fetchWithTimeout
  },
  realtime: {
    // Realtime connection settings for better stability
    params: {
      eventsPerSecond: 10
    }
  }
});